`timescale 1ns/1ps
`default_nettype none

module tb_soc_stub_top;
    localparam int CLK_PERIOD_NS = 10;
    localparam int UART_CLOCKS_PER_BAUD = 25;
    localparam int TIMEOUT_CYCLES = 200000;

    logic clk;
    logic reset;

    logic uart_rx_drive;
    wire  uart_rx_to_dut;
    wire  uart_tx_from_dut;

    wire  spi_mosi;
    wire  spi_miso_ext;
    wire  spi_sclk;
    wire  spi_cs_n;

    wire [1:0] test_phase;
    wire done;
    wire pass;
    wire fail;
    wire [7:0] last_uart_byte;
    wire [7:0] last_spi_byte;
    wire [7:0] error_code;

    // phase 2: UART TX is looped back to UART RX for the 0x13 UART loopback test.
    // Other phases use the external UART source driven by the testbench.
    assign uart_rx_to_dut = (test_phase == 2'd2) ? uart_tx_from_dut : uart_rx_drive;
    // SPI MISO is now generated by the internal SPI slave model in soc_stub_top.
    // The external MISO pin is kept at 0 and is ignored while USE_INTERNAL_SPI_SLAVE=1.
    assign spi_miso_ext = 1'b0;

    soc_stub_top #(
        .UART_CLOCKS_PER_BAUD(UART_CLOCKS_PER_BAUD[15:0]),
        .SPI_CLK_DIV(4),
        .USE_INTERNAL_SPI_SLAVE(1'b1)
    ) dut (
        .i_clk(clk),
        .i_reset(reset),
        .i_uart_rx(uart_rx_to_dut),
        .o_uart_tx(uart_tx_from_dut),
        .i_spi_miso(spi_miso_ext),
        .o_spi_mosi(spi_mosi),
        .o_spi_sclk(spi_sclk),
        .o_spi_cs_n(spi_cs_n),
        .o_test_phase(test_phase),
        .o_done(done),
        .o_pass(pass),
        .o_fail(fail),
        .o_last_uart_byte(last_uart_byte),
        .o_last_spi_byte(last_spi_byte),
        .o_error_code(error_code)
    );

    initial begin
        clk = 1'b0;
        forever #(CLK_PERIOD_NS/2) clk = ~clk;
    end

    task automatic uart_send_byte(input logic [7:0] data);
        int i;
        begin
            // UART 8N1, LSB first
            uart_rx_drive = 1'b0; // start bit
            repeat (UART_CLOCKS_PER_BAUD) @(posedge clk);

            for (i = 0; i < 8; i++) begin
                uart_rx_drive = data[i];
                repeat (UART_CLOCKS_PER_BAUD) @(posedge clk);
            end

            uart_rx_drive = 1'b1; // stop bit
            repeat (UART_CLOCKS_PER_BAUD) @(posedge clk);
            repeat (UART_CLOCKS_PER_BAUD) @(posedge clk);
        end
    endtask

    task automatic send_external_uart_sequence;
        logic [7:0] msg [0:7];
        int i;
        begin
            msg[0] = 8'h31; // '1'
            msg[1] = 8'h32; // '2'
            msg[2] = 8'h33; // '3'
            msg[3] = 8'h34; // '4'
            msg[4] = 8'h35; // '5'
            msg[5] = 8'h36; // '6'
            msg[6] = 8'h37; // '7'
            msg[7] = 8'h38; // '8'

            $display("[TB] External UART source sends: 12345678");
            for (i = 0; i < 8; i++) begin
                uart_send_byte(msg[i]);
            end
        end
    endtask

    initial begin
        $dumpfile("tb_soc_stub_top.vcd");
        $dumpvars(0, tb_soc_stub_top);

        uart_rx_drive = 1'b1;
        reset = 1'b1;
        repeat (10) @(posedge clk);
        reset = 1'b0;
        repeat (20) @(posedge clk);

        // Send the external UART sequence first. The UART RX FIFO stores the bytes
        // while wb_master_stub polls/reads them through Wishbone. Avoid fork/disable
        // constructs here because some Verilator versions emit invalid C++ for SV
        // process handling.
        send_external_uart_sequence();

        for (int timeout_count = 0; timeout_count < TIMEOUT_CYCLES; timeout_count++) begin
            @(posedge clk);
            if (done) begin
                if (pass && !fail) begin
                    $display("ALL SOC STUB TESTS PASSED");
                    $finish;
                end else begin
                    $error("SOC STUB TEST FAILED. error_code=0x%02x last_uart=0x%02x last_spi=0x%02x",
                           error_code, last_uart_byte, last_spi_byte);
                    $finish;
                end
            end
        end

        $error("Timeout waiting for SOC stub test to finish. phase=%0d last_uart=0x%02x last_spi=0x%02x error=0x%02x",
               test_phase, last_uart_byte, last_spi_byte, error_code);
        $finish;
    end
endmodule

`default_nettype wire
